-- Task Reminder System Migration
-- Adds reminder settings and notification tracking for tasks

-- 1. Add reminder configuration columns to tasks table
ALTER TABLE crm.tasks
  ADD COLUMN IF NOT EXISTS reminder_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS reminder_sent_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS reminder_hours_before integer DEFAULT 24;

-- 2. Create reminder preferences table for users
CREATE TABLE IF NOT EXISTS crm.reminder_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_id bigint NOT NULL REFERENCES crm.sales(id) ON DELETE CASCADE,
  email_enabled boolean DEFAULT true,
  default_hours_before integer DEFAULT 24,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(sales_id)
);

-- 3. Create reminder log table for tracking
CREATE TABLE IF NOT EXISTS crm.task_reminder_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES crm.tasks(id) ON DELETE CASCADE,
  sent_at timestamp with time zone DEFAULT now(),
  recipient_email text NOT NULL,
  status text NOT NULL DEFAULT 'sent', -- sent, failed, pending
  error_message text,
  created_at timestamp with time zone DEFAULT now()
);

-- 4. Create index for efficient reminder queries
CREATE INDEX IF NOT EXISTS idx_tasks_reminder_due
  ON crm.tasks(due_date, reminder_sent_at)
  WHERE done_date IS NULL AND reminder_enabled = true;

-- 5. Create view for tasks needing reminders
CREATE OR REPLACE VIEW crm.tasks_pending_reminders AS
SELECT
  t.id,
  t.contact_id,
  t.type,
  t.text,
  t.due_date,
  t.sales_id,
  t.reminder_hours_before,
  s.email AS sales_email,
  s.first_name || ' ' || s.last_name AS sales_name,
  co.first_name || ' ' || co.last_name AS contact_name,
  c.name AS company_name,
  EXTRACT(EPOCH FROM (t.due_date - now())) / 3600 AS hours_until_due
FROM crm.tasks t
LEFT JOIN crm.sales s ON t.sales_id = s.id
LEFT JOIN crm.contacts co ON t.contact_id = co.id
LEFT JOIN crm.companies c ON co.company_id = c.id
WHERE
  t.done_date IS NULL
  AND t.reminder_enabled = true
  AND t.reminder_sent_at IS NULL
  AND t.due_date > now()
  AND EXTRACT(EPOCH FROM (t.due_date - now())) / 3600 <= t.reminder_hours_before;

-- 6. Grant permissions
GRANT SELECT ON crm.reminder_preferences TO authenticated, anon;
GRANT INSERT, UPDATE, DELETE ON crm.reminder_preferences TO authenticated;

GRANT SELECT ON crm.task_reminder_log TO authenticated;
GRANT INSERT ON crm.task_reminder_log TO authenticated;

GRANT SELECT ON crm.tasks_pending_reminders TO authenticated, anon;

-- 7. Enable RLS
ALTER TABLE crm.reminder_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm.task_reminder_log ENABLE ROW LEVEL SECURITY;

-- 8. Create RLS policies
CREATE POLICY "Users can view own reminder preferences"
  ON crm.reminder_preferences FOR SELECT
  TO authenticated
  USING (sales_id = auth.uid()::bigint);

CREATE POLICY "Users can update own reminder preferences"
  ON crm.reminder_preferences FOR UPDATE
  TO authenticated
  USING (sales_id = auth.uid()::bigint);

CREATE POLICY "Users can insert own reminder preferences"
  ON crm.reminder_preferences FOR INSERT
  TO authenticated
  WITH CHECK (sales_id = auth.uid()::bigint);

CREATE POLICY "Users can view own reminder logs"
  ON crm.task_reminder_log FOR SELECT
  TO authenticated
  USING (
    task_id IN (
      SELECT id FROM crm.tasks WHERE sales_id = auth.uid()::bigint
    )
  );

CREATE POLICY "System can insert reminder logs"
  ON crm.task_reminder_log FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- 9. Create function to mark reminder as sent
CREATE OR REPLACE FUNCTION crm.mark_reminder_sent(
  p_task_id bigint,
  p_recipient_email text,
  p_status text DEFAULT 'sent',
  p_error_message text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Update task
  UPDATE crm.tasks
  SET reminder_sent_at = now()
  WHERE id = p_task_id;

  -- Log the reminder
  INSERT INTO crm.task_reminder_log (task_id, recipient_email, status, error_message)
  VALUES (p_task_id, p_recipient_email, p_status, p_error_message);
END;
$$;

COMMENT ON TABLE crm.reminder_preferences IS 'User preferences for task reminder notifications';
COMMENT ON TABLE crm.task_reminder_log IS 'Audit log of all sent task reminders';
COMMENT ON VIEW crm.tasks_pending_reminders IS 'Tasks that need reminder emails sent';
COMMENT ON FUNCTION crm.mark_reminder_sent IS 'Marks a task reminder as sent and logs it';
